# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Taylor's Ruby Blog
email: taylorpeatl@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog started to consolidate my learning as I venture into web development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://taylorpeat.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
